"""init

Revision ID: c67ed6d3d4f0
Revises: 
Create Date: 2023-01-12 20:53:04.163836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = 'c67ed6d3d4f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dislikedpostslink',
    sa.Column('disliker_id', sa.Integer(), nullable=False),
    sa.Column('disliked_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disliked_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['disliker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('disliker_id', 'disliked_post_id')
    )
    op.create_table('likedpostslink',
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['liked_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('liker_id', 'liked_post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likedpostslink')
    op.drop_table('dislikedpostslink')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
